---
name: Docker tags update

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # 23:00 UTC is 7am SGT | 11:00 UTC is 7pm SGT
    - cron: '0 11,23 * * *'

permissions:
  contents: write

env:
  TZ: "Asia/Singapore"

jobs:
  docker-tags-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run bash script
        run: |
          make install
          make update

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Scheduled file updates: Run update.sh" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
